# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('PF', 'Pastoral Formation')], max_length=2)),
                ('venue', models.CharField(max_length=50)),
            ],
        ),
    ]
