# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20160326_1028'),
        ('events', '0002_auto_20160326_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(through='events.Attend', to='members.Member'),
        ),
    ]
