# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='members',
            new_name='attendees',
        ),
    ]
