# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='first_name',
            new_name='family_name',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='last_name',
            new_name='given_name',
        ),
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
