# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20160325_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('B+', 'B+')], max_length=2),
        ),
        migrations.AddField(
            model_name='member',
            name='cell_number',
            field=models.CharField(default='123', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='course',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(default='jat.torres@gmail.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='school',
            field=models.CharField(default='Brent', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='school_level',
            field=models.CharField(default='11', max_length=10),
            preserve_default=False,
        ),
    ]
