# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20160326_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='fathers_contact_details',
            field=models.CharField(blank=True, max_length=100, verbose_name="Father's cell #"),
        ),
        migrations.AddField(
            model_name='member',
            name='fathers_occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name="Father's occupation"),
        ),
        migrations.AddField(
            model_name='member',
            name='mothers_contact_details',
            field=models.CharField(blank=True, max_length=100, verbose_name="Mother's cell #"),
        ),
        migrations.AddField(
            model_name='member',
            name='mothers_occupation',
            field=models.CharField(blank=True, max_length=100, verbose_name="Mother's occupation"),
        ),
        migrations.AddField(
            model_name='member',
            name='name_of_father',
            field=models.CharField(default='Miguel Luciano', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='name_of_mother',
            field=models.CharField(default='Elsie', max_length=100),
            preserve_default=False,
        ),
    ]
